version: 2
registries:
  codeartifact:
    type: npm-registry
    url: https://<domain>-<account>.d.codeartifact.<region>.amazonaws.com
    token: ${{secrets.DEPENDABOT_TOKEN}}
updates:
 - package-ecosystem: "npm"
   directory: "/"
   schedule:
      interval: "weekly"
   registries:
     - codeartifact
